version: '3'

services:
  pwn__bad_shell:
    image: pwn__bad_shell
    container_name: pwn__bad_shell
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40802:9999"