version: '3'
services:
  web:
    build: ./web
    restart: always
    environment:
      - BOT_HOST=bot
      - BOT_PORT=6565
      - HOST=web:8687
      - COOKIE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4ifQ.Lfbps8JgRG8R1HGQYPiXzrNMsZTxvYUVuSz8K98TqLs
      - COOKIEE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiZG9uIn0.S3vunJ_XsNzyCHmSeu6-Xq-AisXzA2K2flMGH6tx_M4
      - FLAG=KMIPNVIPNJ{yEAH_XSS_w1th_CSP_4nd_html_entities_BYp455
      - FLAGG=and_JWTDECOD1NG_00}
    ports:
      - 7132:8687
  bot:
    build: bot
    environment:
      - COOKIE=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiYWRtaW4ifQ.Lfbps8JgRG8R1HGQYPiXzrNMsZTxvYUVuSz8K98TqLs
      - SITE=http://web:8687
      - UsernameAdmin=adminUname
      - REPORT_HOST=web
      - BOT_PORT=6565
    restart: always
