version: '3'

services:
  pwn__gets_the_flag_out:
    image: crypto__pal_signer
    container_name: crypto__pal_signer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40801:9999"
    networks:
      - crypto__pal_signer_network
networks:
  crypto__pal_signer_network:
    driver: bridge
