version: '3'

services:
  pwn__gets_the_flag_out:
    image: pwn__gets_the_flag_out
    container_name: pwn__gets_the_flag_out
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "40801:9999"